#WAP to calculate area of triangle and rectangle
print("Enter the dimensions of triangle")
base = float(input("Enter the base of triangle:"))
height = float(input("Enter the height of triangle:"))
area_triangle = 0.5 * base * height
print("Area of triangle is:", area_triangle ,"sq units")
print("Enter the dimensions of rectangle")
length = float(input("Enter the length of rectangle:"))
breadth = float(input("Enter the breadth of rectangle:"))
area_rectangle = length * breadth
print("Area of rectangle is:", area_rectangle ,"sq units")
